---
name: "Linting"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: flake8 Lint
        uses: py-actions/flake8@v2