---
name: "Linting"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "*"
      
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          use-flake8: true